---
title: "Presentations and Posters"
---

```{r}
#| include: false
# note: it seems that the best way to get this to work with my computer's permissions is to render this one page on windows and then render the rest. 
```

```{r echo=FALSE}
#| include: false
#| 
library(tidyverse)
library(kableExtra)
M <- read.csv('./data/004_PosterList_Draft1.csv')

subset_M <- function(x = "Biochemical and Molecular Genetics"){
  tmp <- M |> 
    filter(Category == x) |> 
    select(Poster.Number, Individual, Email, Description) |>
    rename(Poster = Poster.Number)
  # reformat as mailto 
  # tmp$Email <- paste0('[', tmp$Email,'](', 'mailto:', str_replace(str_replace(tmp$Email, '<', ''), '>', ''), ']')
  
  out <- kbl(tmp) |>
    kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
  return(out)
}
```

## Biochemical and Molecular Genetics

```{r echo=FALSE}
subset_M(x = 'Biochemical and Molecular Genetics')
```

## Cell and Developmental Biology

```{r echo=FALSE}
subset_M(x = 'Cell and Developmental Biology')
```

## Computational and Large-Scale Biology

```{r echo=FALSE}
subset_M(x = 'Computational and Large-Scale Biology')
```

## Cytogenetics

```{r echo=FALSE}
subset_M(x = 'Cytogenetics')
```

## Education & Outreach

```{r echo=FALSE}
subset_M(x = 'Education & Outreach')
```

## Quantitative Genetics & Breeding

```{r echo=FALSE}
subset_M(x = 'Quantitative Genetics & Breeding')
```

## Transposons & Epigenetics

```{r echo=FALSE}
subset_M(x = 'Transposons & Epigenetics')
```

## Evolution and Population Genetics

```{r echo=FALSE}
subset_M(x = 'Evolution and Population Genetics')
```

## Late Poster Submissions

```{r echo=FALSE}
subset_M(x = 'Late Poster Submissions')
```
